export const theme = {
  bg: "#f5f5f0",
  card: "#ffffff",
  primary: "#1a1a2e",
  accent: "#e63946",
  text: "#1a1a2e",
  textLight: "#6b7280",
  border: "#e5e5e0",
  inputBg: "#fafaf8",
};

export const styles = {
  app: {
    fontFamily: "'Segoe UI', Tahoma, Geneva, Verdana, sans-serif",
    background: theme.bg,
    minHeight: "100vh",
    color: theme.text,
  },
  nav: {
    background: theme.primary,
    padding: "0 32px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    height: "60px",
    position: "sticky",
    top: 0,
    zIndex: 100,
  },
  logo: {
    color: "#fff",
    fontSize: "20px",
    fontWeight: "700",
    letterSpacing: "1px",
    display: "flex",
    alignItems: "center",
    gap: "8px",
  },
  logoAccent: {
    color: theme.accent,
  },
  navLinks: {
    display: "flex",
    gap: "4px",
  },
  navLink: (active) => ({
    color: active ? "#fff" : "#a0a0b8",
    background: active ? "rgba(230,57,70,0.2)" : "transparent",
    border: "none",
    padding: "8px 16px",
    borderRadius: "6px",
    cursor: "pointer",
    fontSize: "14px",
    fontWeight: active ? "600" : "400",
    transition: "all 0.2s",
    fontFamily: "inherit",
  }),
  container: {
    maxWidth: "1000px",
    margin: "0 auto",
    padding: "24px",
  },
  pageTitle: {
    fontSize: "26px",
    fontWeight: "700",
    marginBottom: "20px",
    color: theme.primary,
  },
  card: {
    background: theme.card,
    borderRadius: "10px",
    border: `1px solid ${theme.border}`,
    padding: "20px",
    marginBottom: "16px",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
    fontSize: "14px",
  },
  th: {
    textAlign: "left",
    padding: "10px 12px",
    borderBottom: `2px solid ${theme.primary}`,
    fontSize: "12px",
    fontWeight: "700",
    textTransform: "uppercase",
    letterSpacing: "0.5px",
    color: theme.textLight,
  },
  td: {
    padding: "10px 12px",
    borderBottom: `1px solid ${theme.border}`,
    verticalAlign: "middle",
  },
  badge: (status) => {
    const colors = {
      Active: { bg: "#d4edda", color: "#155724" },
      "Under Maintenance": { bg: "#fff3cd", color: "#856404" },
      Retired: { bg: "#f8d7da", color: "#721c24" },
    };
    const c = colors[status] || { bg: "#e2e3e5", color: "#383d41" };
    return {
      display: "inline-block",
      padding: "3px 10px",
      borderRadius: "12px",
      fontSize: "12px",
      fontWeight: "600",
      background: c.bg,
      color: c.color,
    };
  },
  btnPrimary: {
    background: theme.accent,
    color: "#fff",
    border: "none",
    padding: "10px 20px",
    borderRadius: "6px",
    cursor: "pointer",
    fontSize: "14px",
    fontWeight: "600",
    fontFamily: "inherit",
    transition: "background 0.2s",
  },
  btnSecondary: {
    background: "transparent",
    color: theme.primary,
    border: `1px solid ${theme.border}`,
    padding: "6px 14px",
    borderRadius: "6px",
    cursor: "pointer",
    fontSize: "13px",
    fontFamily: "inherit",
    marginRight: "6px",
  },
  btnDanger: {
    background: "transparent",
    color: theme.accent,
    border: `1px solid ${theme.accent}`,
    padding: "6px 14px",
    borderRadius: "6px",
    cursor: "pointer",
    fontSize: "13px",
    fontFamily: "inherit",
  },
  input: {
    width: "100%",
    padding: "9px 12px",
    border: `1px solid ${theme.border}`,
    borderRadius: "6px",
    fontSize: "14px",
    fontFamily: "inherit",
    background: theme.inputBg,
    boxSizing: "border-box",
  },
  select: {
    width: "100%",
    padding: "9px 12px",
    border: `1px solid ${theme.border}`,
    borderRadius: "6px",
    fontSize: "14px",
    fontFamily: "inherit",
    background: theme.inputBg,
    boxSizing: "border-box",
  },
  label: {
    display: "block",
    fontSize: "13px",
    fontWeight: "600",
    marginBottom: "4px",
    color: theme.textLight,
  },
  formGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "16px",
  },
  message: (type) => ({
    padding: "12px 16px",
    borderRadius: "8px",
    marginBottom: "16px",
    fontSize: "14px",
    background: type === "success" ? "#d4edda" : type === "error" ? "#f8d7da" : "#cce5ff",
    color: type === "success" ? "#155724" : type === "error" ? "#721c24" : "#004085",
    border: `1px solid ${type === "success" ? "#c3e6cb" : type === "error" ? "#f5c6cb" : "#b8daff"}`,
  }),
  searchBox: {
    display: "flex",
    gap: "10px",
    marginBottom: "20px",
  },
  emptyState: {
    textAlign: "center",
    padding: "40px 20px",
    color: theme.textLight,
  },
  aboutCard: {
    background: theme.card,
    borderRadius: "10px",
    border: `1px solid ${theme.border}`,
    padding: "24px",
    textAlign: "center",
    flex: "1",
    minWidth: "200px",
  },
  aboutAvatar: {
    width: "64px",
    height: "64px",
    borderRadius: "50%",
    background: theme.primary,
    color: "#fff",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "24px",
    fontWeight: "700",
    margin: "0 auto 12px auto",
  },
  paginationBar: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: "8px",
    marginTop: "16px",
  },
  pageBtn: (active) => ({
    padding: "6px 12px",
    border: `1px solid ${active ? theme.accent : theme.border}`,
    background: active ? theme.accent : "#fff",
    color: active ? "#fff" : theme.text,
    borderRadius: "6px",
    cursor: "pointer",
    fontSize: "13px",
    fontWeight: active ? "600" : "400",
    fontFamily: "inherit",
  }),
};
